### ISSUE TITLE
App not opening after first time closing it. 

### ISSUE THREAD

**Issue by Smurisengo** [ethereum-push-notification-service/push-mobile-app#18]
After downloading the app on iOS 15.1.1 and connecting the wallet, I close the app and Im not able to reopen it. 

I had to delete it and redownloaded it, and the issue persists. 
Replicated on
- iOS 15.0.2  

Find below video of behaviour. 

https://user-images.githubusercontent.com/89828356/148500091-487a23fe-dace-4411-ad5f-73726227720b.MP4

**Comment by zaryab2000** [comment]
@MdTeach  check on this and close if already been addressed in recent deployments.
