### ISSUE TITLE
Webapp and iOS app not synced

### ISSUE THREAD

**Issue by Smurisengo** [ethereum-push-notification-service/push-mobile-app#19]
The web app and the iOS app are not synced. 

I opted in to two channels in the web app 
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/89828356/148500531-56babcb7-db33-4259-b646-f73e2fe09ebb.png">

I connect the same wallet to the mobile app and Im not subscribed. 
![IMG_1278](https://user-images.githubusercontent.com/89828356/148500629-ed0d906e-e55f-4ca8-984e-dd226039601d.jpg)

Replicated with two separate wallets

**Comment by zaryab2000** [comment]
@MdTeach  check on this and close if already addressed in recent deployments.
