### ISSUE TITLE
If message sent over 24h ago, display the date the message was sent instead of the hour

### ISSUE THREAD

**Issue by strykerin** [ethereum-push-notification-service/push-mobile-app#45]

**Comment by kalashshah** [comment]
The date is shown above the message section and the message itself shows the time of the day it was sent.

<img width="320" alt="image" src="https://github.com/ethereum-push-notification-service/push-mobile-app/assets/81062983/b57ce36f-c95c-4729-bd5a-eeae13ff38ff">
