### ISSUE TITLE
How you do the ECIES encryption?

### ISSUE THREAD

**Issue by PeterMtCheung** [ethereum-push-notification-service/push-mobile-app#46]
It shows the below error when I use your CryptoHelper file for the encryption in another react native expo app.

TypeError: null is not an object (evaluating 'RNRandomBytes.seed')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:237:40 in guardedLoadModule
at node_modules/eccrypto/browser.js:60:15 in Promise$argument_0
at node_modules/eccrypto/browser.js:59:20 in sha512

**Comment by zaryab2000** [comment]
@MdTeach can you please check on this one ?
